process.shift <- function(dir, idx, new.waves, nearest, window) {
	data("thuillier.completed.by.AM0AM1")
	data("oz.k")
	data("table.Q")
	data("table.f")
	cops <- copsdata(dir)
	copsqaa(cops$Rrs, idx, dir)
	copsshift(cops, new.waves, nearest, window, dir)
	cat("******************************************************************************************************\n")
	cat("In directory ", paste(dir, "shift.cops", sep = "/"), " See :\n")
	cat("----------------------------------------------------------------\n")
	cat("  file cops.waves.dat (original wavelengths)\n")
	cat("  file idx.dat (indexes of original wavelengths for QAA)\n")
	cat("  file nearest.dat\n")
	cat("    (new wavelengths and indexes of the closest original wavelengths)\n")
	cat("  intermediate files qaa.in and qaa.out\n")
	cat("  plots : shift.pdf\n")
	cat("Data are stored in files on.newwaves.dat\n")
	cat("you may execute cops.shift(interactive = FALSE)\n")
	cat("  using files idx.dat and neareast.dat allready created\n")
	cat("  by a precedent interactive call to this function\n")
	cat("******************************************************************************************************\n")
}
